<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,2,1,'5Lqn5ZOB5Lit5b+D');
$cfg_Cs[2]=array(1,2,1,'56e75Yqo55S15rqQ');
$cfg_Cs[3]=array(1,2,1,'5pWw5o2u57q/');
$cfg_Cs[4]=array(1,2,1,'6JOd54mZ6Z+z566x');
$cfg_Cs[5]=array(1,2,1,'5pm66IO96Ieq5ouN5Zmo');
$cfg_Cs[6]=array(1,2,1,'5pm66IO956m/5oi0');
$cfg_Cs[7]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[8]=array(0,1,1,'5paw6Ze75Lit5b+D');
$cfg_Cs[9]=array(0,1,1,'55WZ6KiA5Lit5b+D');
$cfg_Cs[10]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[11]=array(0,1,1,'5LiL6L295Lit5b+D');
?>