<?php
$z[0]=Array("field","",250,269);
$z[0][4]['name']="title";
$z[1]=Array("global","",270,296);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",336,358);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",397,448);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",885,920);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel"," <a class=\"cate_a\" href=\"[field:typeurl/]\">[field:typename/]</a> ",1016,1215);
$z[5][4]['row']="10";
$z[5][4]['type']="son";
$z[5][4]['col']="1";
$z[5][4]['currentstyle']="<a class='cate_a cur' href='~typelink~' ~rel~>~typename~</a>";
$z[6]=Array("field","<img id=\"bImg\" src=\"[field:imgsrc/]\" />",1758,1859);
$z[6][4]['name']="imgurls";
$z[6][4]['alt']="图片输出区";
$z[7]=Array("productimagelist","\n            <li class=\"last\"><img src=\"[field:imgsrc/]\" width='98' height='98' /></li>\n            ",2140,2287);
$z[8]=Array("field","",2484,2503);
$z[8][4]['name']="title";
$z[9]=Array("field","",2538,2556);
$z[9][4]['name']="body";
$z[10]=Array("field","",3027,3048);
$z[10][4]['name']="xiangxi";
$z[11]=Array("field","",3100,3120);
$z[11][4]['name']="canshu";
$z[12]=Array("field","",3179,3197);
$z[12][4]['name']="fuwu";
$z[13]=Array("include","",3244,3281);
$z[13][4]['filename']="footer.htm";

?>