<?php
$z[0]=Array("field","",250,269);
$z[0][4]['name']="title";
$z[1]=Array("global","",270,296);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",336,365);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",404,462);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",900,935);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel"," <a class=\"cate_a\" href=\"[field:typeurl/]\">[field:typename/]</a> ",1080,1279);
$z[5][4]['row']="10";
$z[5][4]['type']="son";
$z[5][4]['col']="1";
$z[5][4]['currentstyle']="<a class='cate_a cur' href='~typelink~' ~rel~>~typename~</a>";
$z[6]=Array("list","\n      <div class=\"list \">\n        <div class=\"img\"><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"280\" height=\"305\"  /></a></div>\n        <div class=\"name\"><a href=\"[field:arcurl/]\">[field:title/]</a></div>\n        <div class=\"brief\">K2</div>\n        <div class=\"more\"><a href=\"[field:arcurl/]\">查看详细 ></a></div>\n      </div>\n      ",1360,1765);
$z[6][4]['pagesize']="12";
$z[6][4]['titlelen']="80";
$z[7]=Array("pagelist","",1857,1913);
$z[7][4]['listitem']="pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",1980,2017);
$z[8][4]['filename']="footer.htm";

?>