<?php
$z[0]=Array("field","",250,269);
$z[0][4]['name']="title";
$z[1]=Array("global","",270,296);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",336,365);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",404,462);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",900,935);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1035,1064);
$z[5][4]['name']="position";
$z[6]=Array("list","\n          <li>\n            <div class=\"name\"><a href=\"[field:arcurl/]\">[field:title/]</div>\n            <div class=\"download\">[field:pubdate function=\"GetDateTimeMK(@me)\" /]</a></div>\n          </li>\n          ",1224,1485);
$z[6][4]['pagesize']="8";
$z[6][4]['titlelen']="80";
$z[7]=Array("pagelist","",1563,1619);
$z[7][4]['listitem']="pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",1666,1703);
$z[8][4]['filename']="footer.htm";

?>