<?php
$z[0]=Array("field","",250,269);
$z[0][4]['name']="title";
$z[1]=Array("global","",270,296);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",336,365);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",404,462);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1033,1068);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1168,1197);
$z[5][4]['name']="position";
$z[6]=Array("include","",4817,4854);
$z[6][4]['filename']="footer.htm";

?>